### PR TITLE
feature - Add serverless tasks and spend

### LINKED ISSUE #36: Model the Serverless Task history
Maybe I'm missing something, but it doesn't seem to appear in my spend tables, the compute credit usage seems to live in `SNOWFLAKE.ACCOUNT_USAGE.SERVERLESS_TASK_HISTORY`, and would be useful for getting the spend tables closer to the finalised billing from Snowflake.
Happy to take a stab at this if you'd like, just figured I'd check this wasn't already covered first 😸

### PR DESCRIPTION
**Pull request by GtheSheep**
Closes #36 

This is very close to matching the invoice I received from Snowflake today, there are slight discrepancies in other spends generated by this package and my final bill though which there seems to be an issue related to?

Let me know if there's other models this should be included in also

### CODE REVIEW

**Comment by GtheSheep** [comment]
whoops! will add mock_data

**Comment by NiallRees** [comment]
> whoops! will add mock_data

This is actually in our warehouse - but if you’re able to provide a sample I can add it for the tests?

**Comment by GtheSheep** [comment]
Hey @ian-whitestone - anytime!
The for some categories, such as Cloud Services, Adjustments, the difference is like ~$1 on a few hundred so may be related to that.
The bigger differences are from Storage ~$10 on a couple hundred spend, and Compute ~$30 on a ~$10k spend.

In the grand scheme of things, not major. I could probably check the compute units to see if they match up just in case

**Comment by NiallRees** [comment]
This is ready to ship @GtheSheep - would you mind adding a changelog entry? [Instructions here](https://github.com/get-select/dbt-snowflake-monitoring#adding-a-changelog-entry).

**Pull request merged**
